# Generated by Django 6.0 on 2025-12-23 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('current_status', models.CharField(choices=[('clock_in', '出勤'), ('absent', '欠勤'), ('break_start', '休憩入り'), ('break_end', '休憩終わり')], default='absent', max_length=20)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('clock_in', '出勤'), ('absent', '欠勤'), ('break_start', '休憩入り'), ('break_end', '休憩終わり')], max_length=20)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.employee')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
